[package]
name = "bot"
version = "0.1.0"
authors = ["Jack Lewis <jack@jacklew.is>"]

[dependencies]
toml = "0.4.10"
serde = "1.0.84"
serde_derive = "1.0.84"
reqwest = "0.9.8"
diesel = "1.3.3"
serde_json = "1.0.35"
percent-encoding = "1.0.1"
ctrlc = "3.1.1"

